baseURL = "http://cloudnative.mx/"
languageCode = "es-mx"
title = "Cloud Native MX"
theme = "hugo-casper3"
googleAnalytics     = "UA-112003442-1"
disqusShortname = "cloudnativemx"

[params]
author = "Cloud Native México"
maker = "Círculo Siete"
makerUrl = "https://circulosiete.com"
logo = "/logo.png"
melogo = "/me.jpg"
about = "Entusiastas de #cloudNative. Estamos aquí para divulgar las prácticas, patrones y herramientas para crear software fabuloso, eficiente, resiliente y con HA."
footerabout = "Entusiastas de #cloudNative. Estamos aquí para divulgar las prácticas, patrones y herramientas para crear software fabuloso, eficiente, resiliente y con HA."

facebook = "http://facebook.com/cloudnativemx"
twitter = "http://twitter.com/cloudnativemx"
github = "http://github.com/cloudnativemx"
meetup = "https://www.meetup.com/Cloud-Native-Mexico/"
slack = "http://slack.cloudnative.mx"
soundcloud = "https://soundcloud.com/cloud-native-mx"
youtube = "https://www.youtube.com/CloudNativeMexico"
spotify = "https://open.spotify.com/show/4PQyVjzcDQuELxi3aNO86e"